### ISSUE TITLE
site does not load

### ISSUE THREAD

**Issue by ProbablyComputingSquid** [arnav-kr/MyrioText#5]
![image](https://github.com/user-attachments/assets/056d139e-b75b-494f-9edc-cfd829c39cdd)
myrio.now.sh site doesn't load
(running on chrome on chromebook)

**Comment by arnav-kr** [comment]
did you try reloading?
or else directly try https://myrio.vercel.app ig vercel keeps having configuration issues with now.sh subdomains and ofter they won't redirect to vercel.app counterparts
